version: '2'
services:
  web:
    volumes:
      - ./app:/app
    ports:
      - "80:80"
    environment:
      - 'RUN=python /app/app.py runserver -d'
    command: python /app/app.py runserver
    # Infinite loop, to keep it alive, for debugging
    # command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"
